### PR TITLE
Support new Github UI

### LINKED ISSUE #133: Support for new interface
A few days ago, GitHub released a [brand-new interface](https://github.blog/changelog/2022-11-09-introducing-an-all-new-code-search-and-code-browsing-experience/) (in beta) to search trough code, with a file tree etc.
But it's not working yet with this extension ! We are missing the icons !!

### PR DESCRIPTION
**Pull request by kiendang**
Fix #133. Only tested on Chrome coz I haven't figure out how to install this extension from local files on Firefox.

Screenshot 2022-11-14 at 12 07 08 PM

### CODE REVIEW

**Comment by gamemaker1** [comment]
You can run it from local files on Firefox by going to `about:debugging` > This Firefox > Load Temporary Add On, then selecting the `manifest.json` file:

image

Note that the background.js and other files needed for the extension to work, need to be in the same folder as the manifest.json file, maybe by using the copy plugin in webpack or something similar :)

**Comment by kiendang** [comment]
Thanks. GitHub just updated the UI a tiny bit so I force-pushed a new commit to adapt to that. Tested with both Chrome and Firefox.

**Review by homerchen19 — APPROVED** [review]
Thank you!

**Comment by dev99problems** [comment]
@kiendang many kudos for shipping this, this is so cool 👏 

I use **Brave** browser on daily basis and even though **I installed the latest 1.4.0** version I still **can not** make it work
with new GitHub UI. Maybe I forgot to reset some extension cache or anything like that? Would be thankful for any piece of advice if you have any on your mind.
image

**Comment by kiendang** [comment]
Hi I just check my browser (firefox) and looks like it doesn't work anymore. Will try to debug this in the coming days when I have time.

**Comment by dev99problems** [comment]
Got it, thanks a lot

**Comment by kiendang** [comment]
@dev99problems just added a new commit in #138 to fix this. You can checkout my fork and install manually in the meantime.

**Comment by dev99problems** [comment]
@kiendang sending many kudos 👏

**Pull request merged**
